### ISSUE TITLE
Run as particular user

### ISSUE THREAD

**Issue by luke-barnett** [blacklabelops/volumerize#12]
By default this seems to be running as the root user, and so creates permissions just for root.

I'm wanting to then sync backup files remotely which requires that a different user is given access to the backed up files. Can we get this so we can specify the user to run the duplicity commands as?

**Comment by blacklabelops** [comment]
I have never tried this. The alpine base image has a script for this. I can try to hook this up.

**Comment by blacklabelops** [comment]
Okay I have tried this but It's not possible. Whereas duplicity is able to run under a specific user, jobber is not able to not run under root.

I will have to replace jobber with crow in order to achieve this.

**Comment by sven-weber** [comment]
I was facing the same issue today. 
I found another solution to make the backup files accessible for synchronization programs. 

You can automatically execute a script after the backup was performed which will adjust the file permissions. 

Add a Script with the following content: 

```bash
#!/bin/bash 
echo "Post Execute" 
chmod -R a+rw /backup
```
This will change the permissions for all files located in the backup folder of the docker container. 

This script can then be mounted to the container via the following volume: 

```
-v <localePathToScript>:/postexecute/backup 
```
