### ISSUE TITLE
when running "docker run --rm blacklabelops/volumerize openssl rand 128 -base64", it failed.

### ISSUE THREAD

**Issue by yangboz** [blacklabelops/volumerize#18]
At Readme.md 's  Symmetric Backup Encryption chapter,

when running "docker run --rm blacklabelops/volumerize openssl rand 128 -base64", it failed with following error messages:

/opt/volumerize/docker-entrypoint.sh: line 50: exec: openssl: not found

**Comment by blacklabelops** [comment]
Yes, that's weird. Looks like openssl package is still there but missing its command line.

**Comment by blacklabelops** [comment]
Openssl command is back.
