### ISSUE TITLE
[feature] automatic named volume backup?

### ISSUE THREAD

**Issue by Andy2244** [blacklabelops/volumerize#21]
I recently tried [bivac](https://github.com/camptocamp/bivac) and the idea of automatically include all named volumes, combined with a blacklist option made a lot of sense to me. I often create new volumes for containers and having to manually add them to a backup list is error prone.

So maybe its worth thinking about adding a similar feature to volumerize, since local filesystem backups do not work in bivac unfortunately.

**Comment by SrZorro** [comment]
I don't think its posible to do this with volumerize, as the volumes need to be added before the container is running. Looks like in the case of bivac they are creating a new container per volume so they can find and hook all the existing volumes.

An option for you could be to make a script that its in charge to start volumerize where you can find all volumes and hook them up to the container before running it.

**Comment by blacklabelops** [comment]
Bivac seems to be a promising tool. I will keep looking for it. The current documentation is rather disappointing. I cannot imagine how this tool works, too many open questions.

**Comment by SrZorro** [comment]
I did a script for your problem, but you should look at the [--filter option](https://docs.docker.com/engine/reference/commandline/volume_ls/#filtering) in the docker volume ls documentation, this script as it is will mount ALL volumes, because tecnically all volumes are named, if you don't give a name, docker will generate one for them.

So if you add --filter "label=backup" at Ln 8, Col 24 of my script and to your volumes add the [--label option](https://docs.docker.com/engine/reference/commandline/volume_create/#options) you could filter the volumes that need to be included.

```bash
#!/bin/bash
cat > $PWD/_`basename "$0"` <<_EOF_
#!/bin/bash

docker run --rm \\
    -e "VOLUMERIZE_SOURCE=/source" \\
    -e "VOLUMERIZE_TARGET=file:///backup" \\
    $(docker volume ls --format "-v {{.Name}}:/source/{{.Name}} \\")
    -v $PWD/backup:/backup \\
    volumerize
_EOF_

exec $PWD/_`basename "$0"`
rm $PWD/_`basename "$0"`
```

Note: My script will create a filed named the same as himself but with a _ in front, and then will be removed.

**Comment by blacklabelops** [comment]
The idea of adding all named volumes is rather alien to me. Volumerize is by concept to be a companion container that can be adjusted to a specific application stack.

If you run multiple stacks on the same system then there should be multiple Volumerize containers. Each container should stop & start applications and databases containers of a stack. Pre- and post scripts can dump databases and perform cleanup tasks on one stack.

Volumerize is no shot-gun-tool for volumes that has magical snapshot abilities.

**Comment by Andy2244** [comment]
@SrZorro thx for the script, will give it a try.

@blacklabelops 
> Volumerize is no shot-gun-tool for volumes that has magical snapshot abilities.

Did not expect it to-be, just comparing my normal workflow and trying to find a backup solution. For my workflow as none professional docker user, its not really feasible to setup/maintain separate container backups, i would simply forget to update or create them. So i was looking for a "fire&forget" solution similar to how watchtower handles updates.

So was just asking if its possible, but seems that's out of Volumerize scope, so not a problem.
