### ISSUE TITLE
/credentials folder its not used for AmazonS3 backups

### ISSUE THREAD

**Issue by SrZorro** [blacklabelops/volumerize#24]
Looks like the `/credentials `folder is only used by Google Drive and not AmazonS3 but in [backends/AmazonS3/README.md](https://github.com/blacklabelops/volumerize/blob/master/backends/AmazonS3/README.md) All docker run examples contain a reference to a volume called `volumerize_credentials` mounted to that folder. 

This is intended for a future feature where the access key and secret key are saved there or its a typo caused by duplicating the GoogleDrive Readme when creating the docs?

**Comment by blacklabelops** [comment]
Must be a typo by duplicating the readme.
