### ISSUE TITLE
Prepost scripts not executed by periodic backups

### ISSUE THREAD

**Issue by SrZorro** [blacklabelops/volumerize#27]
Prepost scripts are not executed by the periodicBackup script called by jobber.

**Comment by SrZorro** [comment]
Found a problem meanwhile fixing this, what `$BACKUP_TYPE` should have? 

In the case of the other scripts, its the script folder name, but in this case the name is "periodicBackup", but periodic backups can be full or incremental depending on what the variable `$VOLUMERIZE_FULL_IF_OLDER_THAN` contains. 

Should `$BACKUP_TYPE`  detect if the current run is incremental or full? Or with "periodicBackup" we are set?

**Comment by SrZorro** [comment]
I think the best option will be to set `$BACKUP_TYPE` to `backup`, as i can't think of a simple way to check the backup type. 

Also i don't think its worth to check it as i can't think of a case where you would need to make something diferent if its an incremental or full backup.

Also for simplicity im going to change `$BACKUP_TYPE` to only have `backup`, `restore` or `verify`, where `backup` its going to be for the scripts `backup`, `backupIncremental`, `backupFull` and `periodicBackup`.

@blacklabelops any thoughts about this change?

**Comment by blacklabelops** [comment]
This env variable should be renamed. `restore` is no `BACKUP_TYPE`. `backup`, `restore` or `verify` are duplicity actions. Correct would be `ACTION_TYPE`. There is also no way to distinguish between a full or incremental backup.

I also against the current folder strategy. It is to error prone to put all bash scripts inside one pre-directory and having those scripts distinguish when they have to run. 

A pre-script for backups should be put inside `preexecute/backup`. A pre-script for restores should be put inside `preexecute/restore`. And I mean `preexecute` not `prexecute`.

I would be also okay with another folder structure proposal.

Afterwards there is no need for `ACTION_TYPE`.

**Comment by blacklabelops** [comment]
What does this do? `\$(basename -- "\$0")`

**Comment by SrZorro** [comment]
Its the script filename

**Comment by blacklabelops** [comment]
Understood

**Comment by SrZorro** [comment]
> A pre-script for backups should be put inside preexecute/backup. A pre-script for restores should be put inside preexecute/restore. And I mean preexecute not prexecute.

This sounds like a good solution, when i have a moment i will refactor it so it uses this structure instead of the variable way.

**Comment by blacklabelops** [comment]
Take your time.

**Comment by SrZorro** [comment]
We should also do something to execute a script before or after the volume shut down? like `preexecute/restore/before` or something like that?

**Comment by blacklabelops** [comment]
I just noticed that prescripts are running after containers stopped? Don't you need a running database for dumping?

**Comment by blacklabelops** [comment]
Do you mean `preexecute/restore/beforeshutdown.sh`?

**Comment by SrZorro** [comment]
> I just noticed that prescripts are running after containers stopped? Don't you need a running database for dumping?

Correct, thats why im speaking about this issue, how we should handle that?

For MySQL we need the running container, but maybe in another case someone would need to do stuff after the container is off

> Do you mean preexecute/restore/beforeshutdown.sh?

We have to chose how to handle that, with a script name?

At this moment all the scripts in the folder are executed in alphabetical order. But we can execute (if exists) `beforeshutdown.sh` before stoping the container and `aftershutdown.sh` after stoping it. And all other scripts can be ignored (helper scripts etc).

**Comment by blacklabelops** [comment]
Cycle: pre-scripts -> stop -> backup -> start -> post-scripts

Then we wait for people who cannot work with this and revise a solution. This we do step by step.

In my experience it's hard to react to unexpected feature request when the features are all over-complex. We keep everything as simple as possible and change when a real world problem occurs.

**Comment by SrZorro** [comment]
Yeah better to work the features as the necessity comes and not trying to cover all edge cases.

**Comment by SrZorro** [comment]
@blacklabelops could you take a look at the merge request when you have a moment? Thanks.

**Comment by blacklabelops** [comment]
What about my review comments?

**Comment by SrZorro** [comment]
By review comments do you mean the ones that you pointed in this thread?

Everything that we spoke here its implemented in the pull request if I didn't miss anything or misunderstood something. Also I fixed the notes from the pull #26 about the case directive (that code doesn't exist anymore, so its "fixed") and I also removed all the upper case and symbolic characters from the logs.

**Comment by blacklabelops** [comment]
This one: https://github.com/blacklabelops/volumerize/pull/31#pullrequestreview-127357642

Maybe I had to submit it before you can see it.
