### ISSUE TITLE
"Local and Remote metadata are synchronized, no sync needed"

### ISSUE THREAD

**Issue by yan0s** [blacklabelops/volumerize#30]
Hello!
I tried the jenkins example:
1) I launch a jenkins docker 
2) add some items
3) backup
4) add some more items
5) stop jenkins container
6) restore

Then I get the following message:

docker run --rm     -v jenkins_volume:/source     -v b_jenkins_volume:/backup:ro     -v cache_volume:/volumerize-cache     -e "VOLUMERIZE_SOURCE=/source"     -e "VOLUMERIZE_TARGET=file:///backup"     blacklabelops/volumerize restore    
---

- name: VolumerizeBackupJob
  cmd: /etc/volumerize/periodicBackup
  time: '0 0 4 * * *'
  onError: Continue
  notifyOnError: false
  notifyOnFailure: false

/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Thu Jun  7 14:34:23 2018

7) start jenkins container

All items are still in jenkins dashboard.
Any ideas?

Thanks in advance!

**Comment by blacklabelops** [comment]
Looks like a dependency problem. I will check.

**Comment by blacklabelops** [comment]
I am unable to reproduce this. Please make sure you have the latest image, execute `docker pull blacklabelops/volumerize`.

**Comment by blacklabelops** [comment]
Okay reproduced and fixed!

**Comment by yan0s** [comment]
Thanks! It works now.
