### ISSUE TITLE
Impossible to use volumerize with backblaze B2

### ISSUE THREAD

**Issue by AndreaGiardini** [blacklabelops/volumerize#34]
The outdated version of duplicity is affected by this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901590

This makes volumerize fail whenever an backup to b2 is triggered

I think updating alpine to 3.8 might solve the problem

**Comment by blacklabelops** [comment]
Verified, b2 is "down" in the current version.

Updating to 3.8 will take a while.

**Comment by blacklabelops** [comment]
Update had been easy, fixed by now.
