### ISSUE TITLE
Support Restore of multiple volumes at once

### ISSUE THREAD

**Issue by sixstringsg** [blacklabelops/volumerize#35]
I see in the docs that backing up multiple volumes at once is supported by mounting multiple local volumes into the /source folder. I haven't found a way, however, to restore those individual volumes back to individual volumes instead of one big volume with multiple sub-folders. Right now I just have a big script that restores each individually, but it would be nice if there were a way to do this natively.

**Comment by blacklabelops** [comment]
Please check #32 for details.
