### ISSUE TITLE
Allow listing of available backups and script to restore from a specific date

### ISSUE THREAD

**Issue by eedrah** [blacklabelops/volumerize#39]
I think I can make the pull request for this, but I might need your help verifying it 😄 

I was going to use this to show the backups:

```
duplicity collection-status file:///backup
```

and then look into if I can reuse your "restore" script to choose the date. If I can, then I'll just add documentation saying this.

Watch this space for the pull request shortly 😀

**Comment by eedrah** [comment]
Pull request made - discussion moved there

**Comment by blacklabelops** [comment]
Thanks for the feature.
