### ISSUE TITLE
Add support for specific date restore

### ISSUE THREAD

**Issue by darron1217** [blacklabelops/volumerize#4]
`duplicity -t 3D --file-to-restore FILENAME scp://uid@other.host/some_dir /home/me/restored_file`
How can I do restoration with specific date?

**Comment by blacklabelops** [comment]
You can always check duplicitie's examples section for the required parameters: http://duplicity.nongnu.org/duplicity.1.html#sect3

Then check the contents of the image's restore script. You can always add Duplicity parameters through the script. Just attach them to your script call. Script parameters are taken as duplicty parameters:

~~~~
$ restore  -t 3D
~~~~

**Comment by darron1217** [comment]
It was my mistake... haha

There was option to pass Duplicity Parameters in README :)
Thanks anyway
