### ISSUE TITLE
Unable to use b2.

### ISSUE THREAD

**Issue by Nutellaeis** [blacklabelops/volumerize#42]
When trying to use B2 I always get the following error:

`AttributeError: B2ProgressListener instance has no attribute '__exit__'`

I think this might be related to this Duplicity bug:
https://bugs.launchpad.net/duplicity/+bug/1785520

Maybe it is as simple as updating to the latest version?

**Comment by blacklabelops** [comment]
Looks good, do a pull request or wait until im back

**Comment by blacklabelops** [comment]
Needs 0.7.18 according to #45 but alpine 3.8 only delivers 0.7.17.

Waiting for new alpine version.

**Comment by blacklabelops** [comment]
New installation routine. Image installs duplicity from homepage. We have now duplicity 0.7.18 and issue should be resolved.

**Comment by Nutellaeis** [comment]
Backup to my B2 Bucket finished without errors. Looking good.
