### ISSUE TITLE
Containers are not restarted on failure

### ISSUE THREAD

**Issue by bswinnerton** [blacklabelops/volumerize#43]
I've noticed that when a backup fails (in my case it's due to the underlying mount point being unavailable), the docker containers that are automatically stopped are not restarted:

```
Local and Remote metadata are synchronized, no sync needed.
Last full backup left a partial set, restarting.
Last full backup date: Thu Sep  6 16:51:36 2018
RESTART: The first volume failed to upload before termination.
         Restart is impossible...starting backup from beginning.
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: none
No signatures found, switching to full backup.
Giving up after 1 attempts. IOError: [Errno 2] No such file or directory: '/backup/duplicity-full.20180906T165246Z.vol1.difftar.gz'
```

Would it be possible to ensure that docker containers are started back up even when there is an error backing up?

**Comment by blacklabelops** [comment]
Yes, that is a good idea.

**Comment by blacklabelops** [comment]
Implemented and available.

**Comment by fri-sch** [comment]
Are you sure that it works? I'm using version 1.2.1 and last night the backup failed to push the data via FTPS (I'm not sure why) and the containers stayed down after the failed backup.

**Comment by fri-sch** [comment]
> The solution has been refactored and tested after issue #56.
> 
> Old script already fails when one of the containers fails to either stop or start or being not available anymore.
> 
> New script ignores docker failures and starts available containers.

Thanks a lot for your work! I will update and check.
