### ISSUE TITLE
Restore only partially working

### ISSUE THREAD

**Issue by andheiberg** [blacklabelops/volumerize#46]
Right I'm being a bit nuts here and playing with volumerize to backup a ghost blog (not sure this is a good idea). In any case I'm experiencing issues. Backing up and restoring has been working great on my developer machine.

Then I wished to deploy it to my server. So I created a docker machine on digtitalocean and up'ed the service on it. After that I did a restore from a backup I had on dropbox. The mysql database was correctly restored, however, the ghost volumes were not. I tried to restore them again and get lots of warning about pre-existing files.

```
docker run --rm     --name volumerize     -v server_heiberg-volume:/source/server_heiberg-volume     -v backup_volume:/backup     -v cache_volume:/volumerize-cache     -e "VOLUMERIZE_SOURCE=/source"     -e "VOLUMERIZE_TARGET=dpbx:///server"     -e "DPBX_ACCESS_TOKEN=q3dUBFFaGn0AAAAAAABpsyQ0kqDy7GJTpcs1rNUf_6JL2WhNfTT5ITqLMYQdSETK"     blacklabelops/volumerize restore
---

- name: VolumerizeBackupJob
  cmd: /etc/volumerize/periodicBackup
  time: '0 0 4 * * *'
  onError: Continue
  notifyOnError: false
  notifyOnFailure: false

Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Fri Sep 14 03:32:46 2018
Error '[Errno 17] File exists' processing server_heiberg-volume/config.development.json
Error '[Errno 17] File exists' processing server_heiberg-volume/content/themes/casper
Error '[Errno 17] File exists' processing server_heiberg-volume/content.orig/themes/casper
Error '[Errno 17] File exists' processing server_heiberg-volume/current
Error '[Errno 17] File exists' processing server_heiberg-volume/versions/2.0.3/node_modules/.bin/acorn
Error '[Errno 17] File exists' processing server_heiberg-volume/versions/2.0.3/node_modules/.bin/analytics
...
Error '[Errno 17] File exists' processing server_heiberg-volume/versions/2.0.3/node_modules/static-eval/node_modules/escodegen/node_modules/.bin/esvalidate
Error '[Errno 17] File exists' processing server_heiberg-volume/versions/2.0.3/node_modules/superagent/node_modules/.bin/mime
Error '[Errno 17] File exists' processing server_heiberg-volume/versions/2.0.3/node_modules/tar/node_modules/.bin/mkdirp
Error '[Errno 17] File exists' processing server_heiberg-volume/versions/2.0.3/node_modules/write/node_modules/.bin/mkdirp
Error '[Errno 17] File exists' processing server_heiberg-volume/versions/2.0.3/node_modules/yargs/node_modules/.bin/window-size
```

I did some digging and found https://github.com/blacklabelops/volumerize/blob/0ad481464380a87a71973a546f1945396d3fb8cc/imagescripts/create_scripts.sh#L86 which suggests this is really a duplicity error.

Which lead me to https://askubuntu.com/questions/594879/duplicity-command-line-restore-usage

> first.. duplicity will never overwrite data while restoring. that is a design choice to protect your data. what you've got to do is to restore to a temporary folder and copy/move the restored data manually to your desired location.

That's not exactly what I was expecting from this tool. The weird thing is that everything was working just fine on my local machine. What am I doing wrong here?

**Comment by blacklabelops** [comment]
Must be permission rights.

Your trying to restore data with permissions A on a machine with permissions B. Check your files.

**Comment by blacklabelops** [comment]
Closed because of inactivity.
