### ISSUE TITLE
Document remove-older-than

### ISSUE THREAD

**Issue by shnorbluk** [blacklabelops/volumerize#47]
In README.md, you should give the time format for remove-older-than or refer to http://duplicity.nongnu.org/duplicity.1.html#toc8 , because it is not specified in your readme.

**Comment by blacklabelops** [comment]
I would be happy about a pull request.

**Comment by shnorbluk** [comment]
Hi,
I've done pull request #49. I wanted to reformulate because the explanation
of how to pass parameters was long after the script list. When one finds a
script he wants to use, it is not obvious to read several paragraphs later
to find which parameters to pass.

Thank you.

Le mer. 19 sept. 2018 12:35, Steffen Bleul <notifications@github.com> a
écrit :
