### ISSUE TITLE
VOLUMERIZE_CONTAINERS stop start order

### ISSUE THREAD

**Issue by dicastro** [blacklabelops/volumerize#48]
I have 2 containers:
 - container_db
 - container_server --link container_db:db

I have volumerize container with variable `VOLUMERIZE_CONTAINERS="container_server container_db"`

I've noticed that the containers in variable `VOLUMERIZE_CONTAINERS` are stopped and started in same order (the order in the list).

Following with the example, `container_server` is stopped at first place, and then `container_db` is stopped. That's the desired behaviour.

However when restarting the containers, `container_server` is started at first, but there is an error that says:

```
Error response from daemon: Cannot link to a non running container: /container_db AS /container_server/db
Error: failed to start containers: container_server
```

I think containers should be __stopped in the indicated order and restarted in reverse order__. What do you think?

**Comment by blacklabelops** [comment]
Thanks for the solution!
