### ISSUE TITLE
Is it possible to add an environment variable to control how many full backups to keep?

### ISSUE THREAD

**Issue by Jack187** [blacklabelops/volumerize#5]
Hello,

thx for the great tool. I started using it today, but I'm missing the option to only save 2 (or n) full backups.

I'm currently using the following environment variables:
-e "VOLUMERIZE_JOBBER_TIME=0 */5 * * * *" \ (for testing purposes all 5 mins a inc backup)
-e "VOLUMERIZE_FULL_IF_OLDER_THAN=1h" (for testing purposes after 1h a fresh full backup)

here is what I found in the duplicity man page:
remove-all-inc-of-but-n-full <count> [--force] <url>
Delete incremental sets of all backups sets that are older than the count:th last full backup (in other words, keep only old full backups and not their increments). count must be larger than zero. A value of 1 means that only the single most recent backup chain will be kept intact. Note that --force will be needed to delete the files instead of just listing them.

As I'm new to docker, Is there a way to achieve this with the current version of volumerize or is it something that needs to be added?

Thx for your work!

Bye,
Jack

**Comment by blacklabelops** [comment]
Do we still need something in this ticket?

**Comment by darron1217** [comment]
@Jack187 I think this is solved by https://github.com/blacklabelops/volumerize/issues/7

What do you think?

**Comment by blacklabelops** [comment]
In this form I think it is solved by #7. 

Later on we can think about a Maintenance Mode where you can define several parameters for maintaining long time backup archives.

**Comment by Jack187** [comment]
Yes, it's solved!

I tested it with following configuration:

-e "JOB_NAME2=RemoveAllButNFull" \
-e "JOB_COMMAND2=/etc/volumerize/remove-all-but-n-full 2 --force" \

Thanks for adding! I really appreciate it.

Cheers
Jack
