### ISSUE TITLE
Update Duplicity to  0.7.18.1

### ISSUE THREAD

**Issue by windsource** [blacklabelops/volumerize#53]
I started to use volumerize and ran into the problem described in https://bugs.launchpad.net/duplicity/+bug/1788558. The problem prevents my from using volumerize. It is fixed in Duplicity 0.7.18.1. Could you update volumerize to use the new version?

**Comment by windsource** [comment]
You can find it here: https://launchpad.net/duplicity/+milestone/0.7.18.1.

**Comment by blacklabelops** [comment]
Fixed
