### ISSUE TITLE
Please update to duplicity 0.7.18.2

### ISSUE THREAD

**Issue by windsource** [blacklabelops/volumerize#55]
I am currently affected by the problem described in https://answers.launchpad.net/duplicity/+question/674425 which is fixed in [duplicity 0.7.18.2](https://launchpad.net/duplicity/+milestone/0.7.18.2). Could you please update volumerize to the new version?

**Comment by blacklabelops** [comment]
Done.

**Comment by windsource** [comment]
Thanks!
