### ISSUE TITLE
Support for periodic remove

### ISSUE THREAD

**Issue by darron1217** [blacklabelops/volumerize#6]
It would be nice if we have a way to run remove-older-than periodically :)

How can we achieve it?

**Comment by Jack187** [comment]
Hi darron,

it sounds familiar to the issue that I created.

https://github.com/blacklabelops/volumerize/issues/5

What do you think?

Regards,
Jack

**Comment by darron1217** [comment]
@Jack187 Yep, it seems very silmilar for me, too :)
Anyway, @blacklabelops where are you?
I miss you.... :(

**Comment by blacklabelops** [comment]
Please give me another day :) Ill respond shortly.

**Comment by blacklabelops** [comment]
You can now define jobber cron jobs inside volumerize:

Example:

~~~~
$ docker run -d \
    --name volumerize \
    -v jenkins_volume:/source:ro \
    -v backup_volume:/backup \
    -e "VOLUMERIZE_SOURCE=/source" \
    -e "VOLUMERIZE_TARGET=file:///backup" \
    -e "JOB_NAME2=RemoveOldBackups" \
    -e "JOB_COMMAND2=/etc/volumerize/remove-older-than 3D" \
    -e "JOB_TIME2=0 0 * * * *" \
    blacklabelops/volumerize
~~~~

> Note: Enumerated Jobber tasks must start with number 2 because 1 is held by the periodical backup task.

More details on how Jobber environment variables work: https://github.com/blacklabelops/jobber-cron

> Note: blacklabelops/volumerizes is using Jobber version 1 not 2. I am currently not able to get Jobber running inside alpines latest docker image.

**Comment by darron1217** [comment]
@blacklabelops Wow... the feedback is lightning fast 👍
I've learned many from your code. I really appreciate for that :)

**Comment by blacklabelops** [comment]
Please check functionality and give feedback.

**Comment by darron1217** [comment]
@blacklabelops  Yep, currently I'm testing it :)
It seems working now, but I need more test

**Comment by darron1217** [comment]
@blacklabelops It's working perfectly 👍 
Is it working with X times? 
e.g.
```
JOB_NAME2=RemoveOldBackups
JOB_NAME3=AnotherRemoveOldBackups
JOB_NAME4=YetAnotherRemoveOldBackups
```

**Comment by blacklabelops** [comment]
Yes, you can add as many jobs as you want.

Please close ticket when issue is resolved. It gives a better impression when the ticket owner closes a ticket and not the repository owner.

**Comment by darron1217** [comment]
Thanks a lot :)

**Comment by blacklabelops** [comment]
Info:

- You can list jobs with `jobber list`

- You can test scheduled jobs with `jobber test`
