### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by jlelse** [blacklabelops/volumerize#67]
I want to compile the Docker image on my arm32v7 server and see the Dockerfile uses "blacklabelops/alpine:3.8" as base image. Is there some magic behind this image or can it be easily replaced with the standard alpine image?

**Comment by jlelse** [comment]
Ok thanks, I'll probably have to combine those the two Dockerfiles and exclude everything I don't need.

**Comment by alex-dacosta** [comment]
Hello
I succeeded in doing so. Have a look to issue [https://github.com/blacklabelops/volumerize/issues/83](https://github.com/blacklabelops/volumerize/issues/83) 
Regards
