### ISSUE TITLE
Using this image this Hubic

### ISSUE THREAD

**Issue by krivochenko** [blacklabelops/volumerize#68]
Hi! Thanks for great work! But for me it`s not clever, how to use backends mentioned in Duplicity manual, but not described in backend tutorials in this repo. For example: Hubic.

Thanks for help!

**Comment by blacklabelops** [comment]
Hello, everybody is free to add tutorials for backends!

Personally, I do not know and/or use Hubic.

**Comment by blacklabelops** [comment]
I updated to the latest Duplicity version, you can now consult this for Hubic support: http://duplicity.nongnu.org/vers7/duplicity.1.html#toc16

**Comment by blacklabelops** [comment]
Closed due to inactivity
