### ISSUE TITLE
healthcheck dry-run

### ISSUE THREAD

**Issue by cguentherTUChemnitz** [blacklabelops/volumerize#69]
I there,

i want to docker health-check this backup service itself. Therefor i try to run the script in the --dry-run mode:
`test: "/opt/volumerize/docker-entrypoint.sh backup --dry-run"`

This seems to work fine, unless i am using additionally the VOLUMERIZE_CONTAINERS environment variable. So i have to ask, is the stop and start of the containers defined in VOLUMERIZE_CONTAINERS during dry-run really a desired behavior? I would like to see that those stop and starts are not toggled in the dry-run mode to be able to use this statement as a health-check one.

**Comment by blacklabelops** [comment]
A good question. Do you think that even a dry run can succeed or run properly when the application processes are working on the files in parallel?

I think this is not a proper approach for a "health check". The commands "list" or "verify" are more suitable for health checks.

**Comment by cguentherTUChemnitz** [comment]
I think the list option is a more usable solution. Also it does run a lot faster than doing a full dry run.
