### ISSUE TITLE
Notification on successful backup

### ISSUE THREAD

**Issue by raedle** [blacklabelops/volumerize#70]
Great work! You make an otherwise tedious backup task really simple.

I was wondering if it is somehow possible to automatically send notifications to an email address on successful (or failed) backups?

**Comment by blacklabelops** [comment]
Hello please look here: #59. This repository is deprecated. No feature requests are accepted.

**Comment by blacklabelops** [comment]
Please consult this in order to add your notifications: https://github.com/blacklabelops/volumerize#post-scripts-and-pre-scripts-prepost-strategies

**Comment by blacklabelops** [comment]
Closed due to inactivity.
