### ISSUE TITLE
Question: Should i run one instance of volumerize for each container i want backuped?

### ISSUE THREAD

**Issue by calgara12** [blacklabelops/volumerize#78]
Hey, i just stumpled upon this application and it looks very useful. But im not sure how i should use it.

Lets say i want the data of 2 applications running in docker backuped.

Should i add all volumes accross the 2 applications to a single volumerize instance, or do seperate instances for example run a volumerize_app1 and a volumerize_app2 container?

**Comment by blacklabelops** [comment]
Image supports both.

**Comment by calgara12** [comment]
Ok thanks. Is there a recommended way to do this?

**Comment by blacklabelops** [comment]
Depends on your use case.
