### ISSUE TITLE
Updating the container breaks it

### ISSUE THREAD

**Issue by asitemade4u** [blacklabelops/volumerize#81]
I have updated the container by issuing a `apt update && apt upgrade -y` and it breaks Duplicity.

**Comment by ktechmidas** [comment]
... why the hell would you even do that? The container is runtime, you should be rebuilding the container from the Dockerfile if you want upgraded packages.

Docker was made to avoid this mess, of course running apt in the container breaks it!

**Comment by blacklabelops** [comment]
If an update breaks Duplicity then I assume rebuilding also breaks the image. Means that the distribution and python packages have changed the dependencies.

**Comment by blacklabelops** [comment]
Dockerfile is absolutely outdated:

- Package python-dev does not exist in alpine distribution anymore

- Default python in alpine is now python3

- Duplicity needs new version

- Megatools needs new version

- Azure Package is not available anymore

I have to release a new version.

**Comment by blacklabelops** [comment]
Fixed
