### ISSUE TITLE
Display the name of the source when executing multiple volume backup

### ISSUE THREAD

**Issue by asitemade4u** [blacklabelops/volumerize#82]
When executing a multiple volume backup, the console displays a lot of information but not the source volume, eg.:
```log
Local and Remote metadata are synchronized, no sync needed.
Last full backup date: Tue Apr 21 10:45:21 2020
--------------[ Backup Statistics ]--------------
StartTime 1587737867.32 (Fri Apr 24 10:17:47 2020)
EndTime 1587737867.46 (Fri Apr 24 10:17:47 2020)
ElapsedTime 0.14 (0.14 seconds)
SourceFiles 651
SourceFileSize 9548079 (9.11 MB)
NewFiles 0
NewFileSize 0 (0 bytes)
DeletedFiles 0
ChangedFiles 0
ChangedFileSize 0 (0 bytes)
ChangedDeltaSize 0 (0 bytes)
DeltaEntries 0
RawDeltaSize 0 (0 bytes)
TotalDestinationSizeChange 20 (20 bytes)
Errors 0
-------------------------------------------------
```
When backing up a lot of volumes, the name of the source is critical.
Please add it to the log.

**Comment by blacklabelops** [comment]
Please consult Duplicity for appropriate parameters. Duplicity parameters can easily be added to each command.

E.g. parameter `--verbosity level`

http://duplicity.nongnu.org/vers7/duplicity.1.html

**Comment by hughes123b** [comment]
> Please consult Duplicity for appropriate parameters. Duplicity parameters can easily be added to each command.
> 
> 
> 
> E.g. parameter `--verbosity level`
> 
> 
> 
> http://duplicity.nongnu.org/vers7/duplicity.1.html

**Comment by blacklabelops** [comment]
Closed due to inactivity.
