### ISSUE TITLE
x86_64 only, set it architecture independent?

### ISSUE THREAD

**Issue by alex-dacosta** [blacklabelops/volumerize#83]
Hello
Could you modify it's Dockerfile to set it architecture independent?

I think that you should find a solution to replace this line:
` curl -fSL "https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o /tmp/docker.tgz && `

Thanks & regards

**Comment by alex-dacosta** [comment]
I finally adapted the Dockerfile for my purpose. It compiles and runs on an arm platform (oDroid HC2).
I am currently waiting for the end of the first run, i.e. the "full backup".

[Dockerfile.txt](https://github.com/blacklabelops/volumerize/files/6118662/Dockerfile.txt)

Thanks again

**Comment by alex-dacosta** [comment]
It worked !
```
--------------[ Backup Statistics ]--------------
StartTime 1615398364.50 (Wed Mar 10 17:46:04 2021)
EndTime 1615427057.02 (Thu Mar 11 01:44:17 2021)
ElapsedTime 28692.52 (7 hours 58 minutes 12.52 seconds)
SourceFiles 189413
SourceFileSize 203550644646 (190 GB)
NewFiles 189413
NewFileSize 203550644646 (190 GB)
DeletedFiles 0
ChangedFiles 0
ChangedFileSize 0 (0 bytes)
ChangedDeltaSize 0 (0 bytes)
DeltaEntries 189413
RawDeltaSize 203368126886 (189 GB)
TotalDestinationSizeChange 182204152430 (170 GB)
Errors 0
-------------------------------------------------
```

**Comment by jwillmer** [comment]
Thank you @alex-dacosta for your Dockerfile. I forked the repo and added a build step to get a working ARM docker image based on your file. Have a look at https://github.com/jwillmer/volumerize
