### ISSUE TITLE
Feature Request: ARM Support

### ISSUE THREAD

**Issue by anklav24** [blacklabelops/volumerize#96]
I use Orace ARM VPS and encountered this error when I use your app:
`error standard_init_linux.go:228: exec user process caused: exec format error`

Will you add ARM support in the future?

**Comment by dominikspiertz** [comment]
I also have this issue, as I am trying to backup my smart home system from a raspberry pi 4B. It would be great if we could have an image with ARM support

**Comment by blacklabelops** [comment]
Not planned.
