### ISSUE TITLE
[Update needed] duplicity 0.8.19 no longer compatible with backblaze

### ISSUE THREAD

**Issue by AlexSat** [blacklabelops/volumerize#99]
duplicity 0.8.19 used in volumerize 1.7.1 (https://hub.docker.com/layers/blacklabelops/volumerize/1.7.1/images/sha256-f665ed8ab11497e12dbb462b8fde6a20ea44bb26551d2ec868b8b29f030cca39?context=explore) does not support backblaze b2 for now. Also latest release 1.7.0 does not support backblaze b2 for now too. Need to update duplicity to 0.8.20 (minimum required version):
https://gitlab.com/duplicity/duplicity/-/blob/8f25b8e52bf07926f32fb992656a3bb6c0dae02c/CHANGELOG.md#other-1
> B2sdk 1.8.0 refactored minimum_part_size to recommended_part_size (the value used stays the same) [Adam Jacobs]
It's a breaking change that makes duplicity fail with the new SDK.
This fix makes duplicity compatible with both pre- and post- 1.8.0 SDKs.

Steps to reproduce:
>docker run -d \
    --name volumerize \
    -v volumerize_cache:/volumerize-cache \
    -v jenkins_volume:/source:ro \
    -e "VOLUMERIZE_SOURCE=/source" \
    -e "VOLUMERIZE_TARGET=b2://003945h951emn6p0000000001:H006yG2V7+pogtolEFwCexcZUWJdkNc@volumerizetest/" \
    blacklabelops/volumerize

>docker exec volumerize backup

Actual behaviour:
Exception throws:
>Could not initialize backend: No module named 'b2sdk.download_dest'

Expeted behaviour:
Successfully backed up to backblaze without errors

**Comment by AlexSat** [comment]
I have been build volumerize image with duplicity 0.8.21 (current release) and its worked

**Comment by blacklabelops** [comment]
Thanks for telling.
